POST http://localhost:5005/api/todo/new
Content-Type: application/json

{
    "text": "Too much of anything is good for nothing ",
    "complete": false
}
###############################

GET http://localhost:5005/api/todo

##################################

PUT http://localhost:5005/api/todo/65e58569a68e88a0539472b9

{
    "complete": true
}
